### ISSUE TITLE
v4l2 loopback sink

### ISSUE THREAD

**Issue by SamSpiri** [Volcomix/virtual-background#10]
Hello, is it possible to feed the output to other application as a virtual camera (subj). On linux all video conf software lacks virtual background.

**Comment by Volcomix** [comment]
Hi, I'm not sure to be aware of every detail but I think you will need a TURN server capable of receiving WebRTC streams and to relay them to v4l2 loopback device.
I guess this should be possible but I don't know enough TURN servers to implement it in this demo and it would need to provide server or local software to install which I'd like to avoid in order to keep this project as a static website.

**Comment by SamSpiri** [comment]
Ok, it's far from the goals of the project. Thanks for explaining.
