### ISSUE TITLE
New landscape selfie segmentation model

### ISSUE THREAD

**Issue by benbro** [Volcomix/virtual-background#21]
Google released a new landscape model of the selfie segmentation:
https://google.github.io/mediapipe/solutions/selfie_segmentation
https://github.com/google/mediapipe/tree/master/mediapipe/modules/selfie_segmentation

How does this compares to the mlkit model in this project?
Does selfie_segmentation.js use WebAssembly+SIMD or WebGL2?
Should we use @mediapipe/selfie_segmentation/selfie_segmentation.js or is the model in this project more performant?

**Comment by jpodwys** [comment]
I forked this project and tried the following

1. Force the code to use the [mediapipe landscape model](https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1/selfie_segmentation_landscape.tflite) into this project and
2.  Update `SegmentationConfig.inputResolution`--I tried both `144x256` (as noted in [the docs](https://google.github.io/mediapipe/solutions/selfie_segmentation#models)) and `256x144` just to be sure

In all cases, the output video feed is blurry.
![Screen Shot 2021-06-28 at 11 40 47 AM](https://user-images.githubusercontent.com/5660076/123680239-b4854100-d805-11eb-9767-128e3e14d365.png)

When I saw that the output image is completely blurred, I wanted to check that the generated segmentation mask contained non-zero values. After checking `tflite.HEAPF32` just before it gets passed to `gl.texSubImage2D` in `loadSegmentationStage::render`, I was able to confirm that the provided segmentation mask does include non-zero values.

With this in mind, I'm uncertain what else needs to be done to make this repo compatible with the MediaPipe segmentation model.

**Comment by benbro** [comment]
Maybe we shouldn't resize the input when using this model?
The selfie_segmentation model docs says:
> Segmentation automatically resizes the input image to the desired tensor dimension before feeding it into the ML models.

Can you please share your code?

**Comment by jpodwys** [comment]
Unfortunately, using the camera's native resolution as `inputResolution` (in my case 640x480) is not working.

[Here's the code](https://github.com/jpodwys/virtual-background/tree/media-pipe) (note it's in the `media-pipe` branch of my fork). My fork strips out react and all non-background blur code.

The files you'll be interested in are
* `TFLite.ts`: Imports the MediaPipe landscape model
* `blur.ts`: Sets `inputResolution`

**Comment by jpodwys** [comment]
I also tried using replacing part of the pipeline with part of Media Pipe's [sample segmentation app](https://google.github.io/mediapipe/solutions/selfie_segmentation#javascript-solution-api) just so I could get the segmentation mask directly from their code. I then fed the generated mask into the pipeline in this repo, but I didn't have any luck there either.

**Comment by Volcomix** [comment]
Hi @jpodwys, thank you for experimenting with this model. Just an intuition without investigating the model file, have you tried replacing [this line](https://github.com/jpodwys/virtual-background/blob/b406cf948eb1ba42b6be9a72668b873112ea9655/src/pipelines/webgl2/webgl2Pipeline.ts#L101) by calling `buildLoadSegmentationStage` instead of `buildSoftmaxStage`? I'm wondering if the softmax is part of the model already.

**Comment by jpodwys** [comment]
Thank you for the suggestion, you were right!

So the following works
1. Swap to MediaPipe's model (I'm using [the landscape model](https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1/selfie_segmentation_landscape.tflite))
2. Change `inputResolution` to `256x144` (**not** `144x256` as noted in the docs)
3. Replace `webgl2Pipeline`'s call to `buildSoftmaxStage` with `buildLoadSegmentationStage`

![Screen Shot 2021-06-29 at 10 39 10 AM](https://user-images.githubusercontent.com/5660076/123835836-405ea200-d8c6-11eb-8052-19597e449b7a.png)

The face of a happy dev :)

**Comment by vavilovm** [comment]
Hi @jpodwys, did you check how does the landscape model performance differ from ML Kit?

**Comment by jpodwys** [comment]
My fork uses the landscape MediaPipe model so you can compare this repo's [live demo](https://volcomix.github.io/virtual-background) to my fork's [live demo](https://jpodwys.github.io/virtual-background/).

I also made a [live demo](https://jpodwys.github.io/media-pipe/) that skips the post-processing pipeline and blurs directly via canvas. It has better performance (fps) but less impressive post-processing. That said, the canvas-only blur implementation looks surprisingly good in this demo because the MediaPipe team built softmax directly into their model.
