### ISSUE TITLE
Working on Safari Browser

### ISSUE THREAD

**Issue by NaeemKhan333** [Volcomix/virtual-background#23]
@Volcomix Thank you for nice work . I have a question "Whether this web app is supported on the Safari Browser?" . I have tested on the safari browser but it is not working . Thank you

**Comment by Volcomix** [comment]
Hey @NaeemKhan333, thanks for asking 😄 
This app relies on `webgl2` which needs to be enabled in Safari "Experimental Features" developer menu starting from v10.1 (https://caniuse.com/webgl2). SIMD is not supported though.

**Comment by NaeemKhan333** [comment]
@Volcomix Thank you for reply , if I change webgl2 to webgl will it support the safari browser or not.

**Comment by Volcomix** [comment]
The GLSL shaders are not compatible with webgl so it won't work. Maybe could you just fallback to the canvas implementation on safari rather than loading the webgl2 pipeline by default: https://github.com/Volcomix/virtual-background/blob/8530c56ce419618a3679ca379e76bfd1518a35f5/src/App.tsx#L35

We could detect this case the same way we detect unsupported SIMD, by trying to create a webgl2 context and by disabling the webl2 options if it is not available (plus fallback to canvas).

**Comment by NaeemKhan333** [comment]
Thank you

**Comment by asaf-byondvr** [comment]
Did anyone succeed in running the playground (https://volcomix.github.io/virtual-background) on iPhone iOS 15.1 / 14.8 / 14.7/ etc?
What is the recommended implementation for cases where WEBGL2 isn't available?

> The GLSL shaders are not compatible with webgl so it won't work. Maybe could you just fallback to the canvas implementation on safari rather than loading the webgl2 pipeline by default:
> 
> https://github.com/Volcomix/virtual-background/blob/8530c56ce419618a3679ca379e76bfd1518a35f5/src/App.tsx#L35
> 
> We could detect this case the same way we detect unsupported SIMD, by trying to create a webgl2 context and by disabling the webl2 options if it is not available (plus fallback to canvas).
