### ISSUE TITLE
Cannot Build TFLite Image

### ISSUE THREAD

**Issue by SE2Dev** [Volcomix/virtual-background#48]
Running `yarn build:tflite` on the latest version of the repository results in the following error:
```log
ERROR: /workspace/tflite/BUILD:25:10: Linking tflite-simd failed: (Exit 1): emcc_link.sh failed: error executing command external/emsdk/emscripten_toolchain/emcc_link.sh @bazel-out/wasm-opt/bin/tflite-simd-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
stderr (/root/.cache/bazel/_bazel_root/00533da95dbcbd49bca844bdfd8d02a4/execroot/__main__/bazel-out/_tmp/actions/stderr-3561) exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; skipping
Target //:tflite-simd failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 227.455s, Critical Path: 29.53s
INFO: 1833 processes: 6 internal, 1827 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
error Command failed with exit code 1.
```

**Comment by Volcomix** [comment]
Thank you for reporting the issue @SE2Dev. I did a bisect from tensorflow repo and the error seems to happen since this commit: https://github.com/tensorflow/tensorflow/commit/c884ba40ee16929568047ea4048850d7417a5b0b.

I'm now trying to figure out how to fix the build here.

FYI the error that has been skipped from your command is related to WASM validation, and the output looks like this:
```
[wasm-validator error in function 17] unexpected false: all used features should be allowed, on 
(v128.const i32x4 0x00000000 0x00000000 0x00000000 0x00000000)
[wasm-validator error in function 17] unexpected false: SIMD operation (SIMD is disabled), on 
(v128.store offset=52 align=4
 (local.get $0)
 (local.tee $4
  (v128.const i32x4 0x00000000 0x00000000 0x00000000 0x00000000)
 )
)
[wasm-validator error in function 17] unexpected false: SIMD operation (SIMD is disabled), on 
(v128.store align=4
 (local.tee $2
  (i32.add
   (local.get $0)
   (i32.const 16)
  )
 )
 (local.get $4)
)
[wasm-validator error in function 17] unexpected false: SIMD operation (SIMD is disabled), on 
(v128.store align=4
 (i32.add
  (local.get $0)
  (i32.const 32)
 )
 (local.get $4)
)
...
```

**Comment by Volcomix** [comment]
Running the build in the CI to confirm that it is fixed :hourglass_flowing_sand:

**Comment by benbro** [comment]
Shouldn't the CI build update these files?
https://github.com/Volcomix/virtual-background/tree/main/public/tflite

**Comment by Volcomix** [comment]
The CI was running every night (but I disabled it last month because didn't have time to investigate this build issue before now). I'm gonna re-enable it as soon as the fix is confirmed.

However as I didn't find easy ways to test that the new tflite build is working as expected, I usually test the generated one manually and update it in the repo if it succeeds.

**Comment by Volcomix** [comment]
BTW the CI is generating an artifact but I'm not sure if it is available publicly Are you able to download the latest successful artifact? https://github.com/Volcomix/virtual-background/actions/runs/2924145483

**Comment by benbro** [comment]
Yes, I can download the zip build artifact.
The new tflite-simd.wasm is 3.1MB compared wthh 2.8MB in the old build.
The file size keep increasing.
https://github.com/Volcomix/virtual-background/issues/40

**Comment by Volcomix** [comment]
Thanks for checking the download and the file size. Now I'll need to check what has been added in the wasm file :disappointed:.

**Comment by Volcomix** [comment]
Fix confirmed, the CI that builds tflite in wasm is green again :tada:

**Comment by Volcomix** [comment]
> Yes, I can download the zip build artifact. The new tflite-simd.wasm is 3.1MB compared wthh 2.8MB in the old build. The file size keep increasing. #40

The js files are smaller and contain less useless functions/variables than the previous ones. No new unused Emscripten feature seem to have been added. The wasm files are both larger indeed and they are way too cryptic to figure out what is the difference. I'd say the difference could come from all the new devs that have been done in tensorflow and XNNPACK since the last built but I honestly don't know. Reversing all the commits from tensorflow and XNNPACK repos would be too long for my spare time right now.
