### ISSUE TITLE
Suggested improvement: background rendering

### ISSUE THREAD

**Issue by jezell** [Volcomix/virtual-background#51]
Awesome work here. One note, in practice the pipeline suffers from a problem that browsers won't render the canvas when the tab becomes inactive, which is pretty common in a meeting. One way to solve this is to move the rendering of the pipeline into something like an audio context loop instead of relying on animation frames.

```
function audioTimerLoop(callback, frequency) {

  // AudioContext time parameters are in seconds
  let freq = frequency / 1000;

  let aCtx = new AudioContext();
  // Chrome needs our oscillator node to be attached to the destination
  // So we create a silent Gain Node
  let silence = aCtx.createGain();
  silence.gain.value = 0;
  silence.connect(aCtx.destination);

  let osc;
  let stopped = false;
  
  onOSCend();

  function onOSCend() {
    osc = aCtx.createOscillator();
    osc.onended = onOSCend;
    osc.connect(silence);
    osc.start(0);
    osc.stop(aCtx.currentTime + freq);
    callback(aCtx.currentTime);
    if (stopped) {
      osc.onended = function() {
        return;
      };
    }
  };
  // return a function to stop our loop
  return function() {
    stopped = true;
  };
}```

**Comment by Volcomix** [comment]
Hi @jezell and thanks for reporting. We recently had similar discussions on another issue: #25.
Indeed 2 solutions seem to arise from the net, the audio timer loop that you shared and the timer in worker.

I'll probably work soon on the timer in worker solution, mostly because that's how GMeet is doing for virtual backgrounds and also because it seems less prone to add work on the main thread.

Perhaps do you have some pros/cons to share regarding both solutions that might help to choose differently?
